# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'brakeman', require: false
  gem 'rspec-rails', '~> 7.0'
  gem 'rubocop', '~> 1.60', require: false
  gem 'rubocop-rails', '~> 2.23', require: false
  gem 'rubocop-rspec', '~> 3.5', require: false
  gem 'simplecov', require: false
  gem 'sqlite3', '~> 2.0'
end
